version: '3'

services:

   spring-petclinic:
      build:
         context: spring-petclinic
      image: spring-petclinic:1.0
      ports:
         - "8080:8080"
         - "9090:9090"
      deploy:
         resources:
            limits:
               memory: 256M
            reservations:
               memory: 256M
      command: ["-Dcom.sun.management.jmxremote.rmi.port=9090", "-Dcom.sun.management.jmxremote=true", "-Dcom.sun.management.jmxremote.port=9090", 
                "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.authenticate=false", 
                "-Dcom.sun.management.jmxremote.local.only=false", "-Djava.rmi.server.hostname=localhost",
                "-XX:+UnlockDiagnosticVMOptions", "-XX:+DebugNonSafepoints", "-XX:+FlightRecorder",
                "-XX:StartFlightRecording=disk=true,filename=/app/recording.jfr,settings=profile,name=jfr-demo", "-jar", "/app/app.jar"]

